---
- name: Configure smth
  hosts: webservers
  gather_facts: no
  remote_user: 'root'
  become_user: 'root'
  become: yes
  tasks:
    - debug:
        msg:
          - "wildfly_startup_wait is {{ wildfly_startup_wait }}"
          - "wildfly_shutdown_wait is {{ wildfly_shutdown_wait }}"

    - name: copy wildfly config file
      template:
        src: 'wildfly.conf.j2'
        dest: '~/wildfly.conf'

    - name: copy nifi config file
      template:
        src: 'nifi.conf.j2'
        dest: '~/nifi.conf'

#    - name: copy nifi config file failed
#      template:
#        src: 'nifi.conff.j2'
#        dest: '~/nifi.conf'
