---
- hosts: webservers
  gather_facts: no
  ignore_errors: yes
  tasks:
  - name: stop httpd
    service:
      name: httpd
      state: started

  - name: uninstall httpd
    yum:
        name: httpd
        state: absent
