---
    - name: Configure smth
      hosts: webservers
      remote_user: 'root'
      become_user: 'root'
      become: yes
      tasks:
        - name: copy main config file
          template:
            src: 'wildfly.conf.j2'
            dest: '~/wildfly.conf'