---
    - name: Configure smth
      hosts: all
      remote_user: 'root'
      become_user: 'root'
      become: yes
      tasks:
        - name: copy wildfly config file
          template:
            src: 'wildfly.conf.vault.j2'
            dest: '~/wildfly.conf'