---
- name: Configure smth
  hosts: all
  gather_facts: no
  remote_user: 'root'
  become_user: 'root'
  become: yes
  tasks:
    - name: copy wildfly config file
      template:
        src: 'wildfly.conf.j2'
        dest: '~/wildfly.conf'
      tags: wildfly

    - name: copy nifi config file
      template:
        src: 'nifi.conf.j2'
        dest: '~/nifi.conf'
      tags: nifi